@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System(autenticacao_gerenciamento, "Sistema de Autenticação e Gerenciamento de Usuários", "Autenticações de toda a aplicação e seus componentes", "")
System(pagamentos, "Sistema de Pagamentos", "Gerenciamento dos pagamentos", "")
System(estoque, "Sistema de Estoque", "Controle dos produtos disponíveis", "")
System(pedidos, "Sistema de Pedidos", "Pedido,catálogo e recomendações", "")
System(avaliacao_comentarios, "Sistema de Avaliação e Comentários", "", "")


Rel(autenticacao_gerenciamento,pedidos,"Dados do usuário","")
Rel(autenticacao_gerenciamento,pagamentos,"Dados do usuário","")
Rel(autenticacao_gerenciamento,avaliacao_comentarios,"Dados do usuário","")
Rel(autenticacao_gerenciamento,estoque,"Dados do administrador/usuário","")

Rel(pedidos,pagamentos,"Dados do pagamento","")
Rel(pagamentos,pedidos,"Confirmação do pagamento","")

Rel(estoque,pedidos,"Se o produto está disponível","")


@enduml